// Generated from docs/Readable_Product_SKU_List.md (names and SKUs). Prices are sample values in whole taka.
export interface DemoProduct { category: string; name: string; sku: string; retail: number }

export const DEMO_PRODUCTS: DemoProduct[] = [
  { category: "Marks Powder Milk", name: "Marks Powder Milk 2 KG", sku: "MARKS-PM-2KG", retail: 1400 },
  { category: "Marks Powder Milk", name: "Marks Powder Milk 1 KG Box", sku: "MARKS-PM-1KG-BOX", retail: 700 },
  { category: "Marks Powder Milk", name: "Marks Powder Milk 1 KG", sku: "MARKS-PM-1KG", retail: 700 },
  { category: "Marks Powder Milk", name: "Marks Powder Milk 500 G", sku: "MARKS-PM-500G", retail: 350 },
  { category: "Marks Powder Milk", name: "Marks Powder Milk 400 G", sku: "MARKS-PM-400G", retail: 280 },
  { category: "Marks Powder Milk", name: "Marks Powder Milk 250 G", sku: "MARKS-PM-250G", retail: 175 },
  { category: "Marks Powder Milk", name: "Marks Powder Milk 200 G", sku: "MARKS-PM-200G", retail: 140 },
  { category: "Marks Powder Milk", name: "Marks Powder Milk 100 G", sku: "MARKS-PM-100G", retail: 70 },
  { category: "Marks Powder Milk", name: "Marks Powder Milk 75 G", sku: "MARKS-PM-75G", retail: 74 },
  { category: "Marks Powder Milk", name: "Marks Powder Milk 20 G", sku: "MARKS-PM-20G", retail: 20 },
  { category: "Marks Powder Milk", name: "Marks Powder Milk 15 G", sku: "MARKS-PM-15G", retail: 15 },
  { category: "Marks Powder Milk", name: "Marks Powder Milk 8 G", sku: "MARKS-PM-8G", retail: 8 },
  { category: "Ama Milk", name: "Ama Milk UHT 1 L", sku: "AMA-UHT-1L", retail: 680 },
  { category: "Ama Milk", name: "Ama Milk 2 KG", sku: "AMA-MILK-2KG", retail: 1360 },
  { category: "Ama Milk", name: "Ama Milk 1 KG", sku: "AMA-MILK-1KG", retail: 680 },
  { category: "Ama Milk", name: "Ama Milk 500 G", sku: "AMA-MILK-500G", retail: 340 },
  { category: "Ama Milk", name: "Ama Milk 400 G", sku: "AMA-MILK-400G", retail: 270 },
  { category: "Ama Milk", name: "Ama Milk 250 G", sku: "AMA-MILK-250G", retail: 170 },
  { category: "Ama Milk", name: "Ama Milk 200 G", sku: "AMA-MILK-200G", retail: 135 },
  { category: "Ama Milk", name: "Ama Milk 100 G", sku: "AMA-MILK-100G", retail: 70 },
  { category: "Ama Milk", name: "Ama Milk 50 G", sku: "AMA-MILK-50G", retail: 48 },
  { category: "Ama Milk", name: "Ama Milk 10 G", sku: "AMA-MILK-10G", retail: 10 },
  { category: "SS Products", name: "SS Milk 2 KG", sku: "SS-MILK-2KG", retail: 1280 },
  { category: "SS Products", name: "SS Milk 1 KG", sku: "SS-MILK-1KG", retail: 640 },
  { category: "SS Products", name: "SS Milk 500 G", sku: "SS-MILK-500G", retail: 320 },
  { category: "SS Products", name: "SS Milk 400 G", sku: "SS-MILK-400G", retail: 255 },
  { category: "SS Products", name: "SS Milk 250 G", sku: "SS-MILK-250G", retail: 160 },
  { category: "SS Products", name: "SS Milk 200 G", sku: "SS-MILK-200G", retail: 130 },
  { category: "SS Products", name: "SS Milk 75 G", sku: "SS-MILK-75G", retail: 67 },
  { category: "SS Products", name: "SS Milk 10 G", sku: "SS-MILK-10G", retail: 9 },
  { category: "SS Products", name: "SS Milk 5 G", sku: "SS-MILK-5G", retail: 5 },
  { category: "All Coffee", name: "Ama Coffee Mix 1 KG", sku: "AMA-COFFEE-MIX-1KG", retail: 1400 },
  { category: "All Coffee", name: "Cup 120 ML", sku: "CUP-120ML", retail: 170 },
  { category: "All Coffee", name: "Cup 150 ML", sku: "CUP-150ML", retail: 210 },
  { category: "All Coffee", name: "Sugar Free Coffee 500 G", sku: "SUGARFREE-COFFEE-500G", retail: 700 },
  { category: "All Coffee", name: "Sugar Free Coffee 15 G", sku: "SUGARFREE-COFFEE-15G", retail: 29 },
  { category: "All Coffee", name: "Masala Tea", sku: "MASALA-TEA", retail: 1400 },
  { category: "All Coffee", name: "Ama Mix 15 G", sku: "AMA-MIX-15G", retail: 29 },
  { category: "All Coffee", name: "Ama 15 G Pouch", sku: "AMA-15G-POUCH", retail: 29 },
  { category: "All Coffee", name: "A Classic 1 G Box", sku: "ACLASSIC-1G-BOX", retail: 5 },
  { category: "All Coffee", name: "A Classic 1 G", sku: "ACLASSIC-1G", retail: 5 },
  { category: "All Coffee", name: "A Soluble 0.75 G", sku: "ASOLUBLE-0.75G", retail: 5 },
  { category: "All Coffee", name: "15 G C Pouch / 25 Pack", sku: "C-POUCH-15G-25PK", retail: 29 },
  { category: "All Coffee", name: "Tea Mix 1 KG", sku: "TEA-MIX-1KG", retail: 1400 },
  { category: "All Coffee", name: "15 G Tea Mix Pouch Pack", sku: "TEA-MIX-15G-POUCH", retail: 29 },
  { category: "Tea", name: "S BOP Tea 500 G", sku: "SBOP-TEA-500G", retail: 260 },
  { category: "Tea", name: "SB Leaf Tea 500 G", sku: "SBLEAF-TEA-500G", retail: 260 },
  { category: "Tea", name: "SS BOP Tea Stall Pack", sku: "SSBOP-TEA-STALL", retail: 520 },
  { category: "Tea", name: "Supreme Tea 500 G", sku: "SUPREME-TEA-500G", retail: 260 },
  { category: "Tea", name: "Tea 500 G", sku: "TEA-500G", retail: 260 },
  { category: "Tea", name: "Tea 250 G", sku: "TEA-250G", retail: 130 },
  { category: "Tea", name: "PD/RD Tea 500 G", sku: "PDRD-TEA-500G", retail: 260 },
  { category: "Tea", name: "Tea 500 G BOP", sku: "TEA-BOP-500G", retail: 260 },
  { category: "Tea", name: "Tea 500 G", sku: "TEA-500G-2", retail: 260 },
  { category: "Tea", name: "Tea 400 G", sku: "TEA-400G", retail: 210 },
  { category: "Tea", name: "Tea 200 G", sku: "TEA-200G", retail: 105 },
  { category: "Tea", name: "Tea 100 G", sku: "TEA-100G", retail: 50 },
  { category: "Tea", name: "Tea 50 G", sku: "TEA-50G", retail: 36 },
  { category: "Tea", name: "Tea 14 G", sku: "TEA-14G", retail: 10 },
  { category: "Tea", name: "Tea 6.5 G", sku: "TEA-6.5G", retail: 5 },
  { category: "Tea", name: "DCTB Saver", sku: "DCTB-SAVER", retail: 520 },
  { category: "Tea", name: "DCTB Tea", sku: "DCTB-TEA", retail: 520 },
  { category: "Tea", name: "Bag-in-Bag Tea", sku: "BAG-IN-BAG-TEA", retail: 520 },
  { category: "Tea", name: "Green Tea", sku: "GREEN-TEA", retail: 520 },
  { category: "MPP / Milk Powder Products", name: "AS Milk Powder 400 G", sku: "MPP-AS-400G", retail: 260 },
  { category: "MPP / Milk Powder Products", name: "AS 2-in-1 Milk Powder 400 G", sku: "MPP-AS-2IN1-400G", retail: 260 },
  { category: "MPP / Milk Powder Products", name: "YS Milk Powder 400 G", sku: "MPP-YS-400G", retail: 260 },
  { category: "MPP / Milk Powder Products", name: "MG Milk Powder 400 G", sku: "MPP-MG-400G", retail: 260 },
  { category: "MPP / Milk Powder Products", name: "MD Milk Powder 400 G", sku: "MPP-MD-400G", retail: 260 },
  { category: "MPP / Milk Powder Products", name: "Milk Tin 1 KG", sku: "MILK-TIN-1KG", retail: 650 },
  { category: "MPP / Milk Powder Products", name: "MDia Milk Tin 400 G", sku: "MDIA-MILK-TIN-400G", retail: 260 },
  { category: "Shah Food / Noodles", name: "Shah Food 1 Pack Noodles", sku: "SHAH-NOODLES-1PK", retail: 180 },
  { category: "Shah Food / Noodles", name: "Shah Food 12 Pack Noodles", sku: "SHAH-NOODLES-12PK", retail: 180 },
  { category: "Beverages", name: "Vibe", sku: "VIBE-DRINK", retail: 110 },
  { category: "Beverages", name: "Drinkon", sku: "DRINKON-DRINK", retail: 110 },
];
